-- Open Hangar app tables (auth tables are in 0001, generated by Better Auth).

-- Linking an extension: the extension asks for a code pair; the signed-in user
-- types the short user_code on /link; the extension polls with device_code and
-- receives its sync token once.
create table "device_code" (
  "device_code" text not null primary key,
  "user_code" text not null unique,
  "user_id" text references "user" ("id") on delete cascade,
  "created_at" integer not null,
  "expires_at" integer not null,
  "approved_at" integer
);

-- Long-lived tokens an extension uses to sync. Only a SHA-256 hash is stored.
create table "sync_token" (
  "id" text not null primary key,
  "user_id" text not null references "user" ("id") on delete cascade,
  "token_hash" text not null unique,
  "label" text,
  "created_at" integer not null,
  "last_used_at" integer
);
create index "sync_token_user_idx" on "sync_token" ("user_id");

-- The latest synced hangar per user (the same JSON as the extension's backup).
create table "hangar_snapshot" (
  "user_id" text not null primary key references "user" ("id") on delete cascade,
  "synced_at" integer not null,
  "size" integer not null,
  "payload" text not null
);
