// Writes site/stars.css: the same drifting-stars backdrop as app.openhangar.space
// (SpaceBackdrop.astro in the private open-hangar-app repo), so the two sites match. Stars come from a
// fixed seed, so the file only changes if this script does.
//   node scripts/site-stars.mjs
import fs from 'node:fs';

const FIELD = 2000;
function rng(seed) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const TINTS = ['255,255,255', '255,255,255', '255,255,255', '207,227,255', '255,231,194'];
function stars(count, seed, minAlpha) {
  const r = rng(seed);
  return Array.from({ length: count }, () => {
    const x = Math.round(r() * FIELD);
    const y = Math.round(r() * FIELD);
    const a = (minAlpha + r() * (1 - minAlpha)).toFixed(2);
    return `${x}px ${y}px rgba(${TINTS[Math.floor(r() * TINTS.length)]},${a})`;
  }).join(',');
}

const css = `/* Generated by scripts/site-stars.mjs: do not edit by hand.
   Three layers of stars drifting upward at different speeds, a few twinkling, over a
   soft blue nebula. Same sky as app.openhangar.space. Motion stops for
   prefers-reduced-motion. */
.space {
  position: fixed;
  inset: 0;
  z-index: -1;
  overflow: hidden;
  pointer-events: none;
}
.space .nebula {
  position: absolute;
  inset: -20%;
  background:
    radial-gradient(38% 30% at 72% 22%, rgba(47, 129, 247, 0.55), transparent 70%),
    radial-gradient(34% 28% at 20% 70%, rgba(135, 90, 240, 0.5), transparent 70%),
    radial-gradient(25% 20% at 55% 55%, rgba(40, 170, 230, 0.4), transparent 70%);
  filter: blur(60px);
  opacity: 0.22;
  animation: oh-breathe 40s ease-in-out infinite alternate;
}
.space .layer,
.space .layer::after {
  position: absolute;
  top: 0;
  left: 0;
  border-radius: 50%;
  background: transparent;
}
.space .layer::after {
  content: '';
  top: ${FIELD}px;
  width: 100%;
  height: 100%;
}
.space .far,
.space .far::after {
  width: 1px;
  height: 1px;
  box-shadow: ${stars(380, 7, 0.25)};
}
.space .far {
  animation: oh-drift 260s linear infinite;
}
.space .mid,
.space .mid::after {
  width: 1.5px;
  height: 1.5px;
  box-shadow: ${stars(130, 19, 0.4)};
}
.space .mid {
  animation:
    oh-drift 170s linear infinite,
    oh-twinkle 6s ease-in-out infinite alternate;
}
.space .near,
.space .near::after {
  width: 2px;
  height: 2px;
  box-shadow: ${stars(40, 31, 0.6)};
}
.space .near {
  animation: oh-drift 110s linear infinite;
}
@keyframes oh-drift {
  to {
    transform: translateY(-${FIELD}px);
  }
}
@keyframes oh-twinkle {
  to {
    opacity: 0.55;
  }
}
@keyframes oh-breathe {
  to {
    opacity: 0.32;
    transform: scale(1.06);
  }
}
@media (prefers-reduced-motion: reduce) {
  .space .nebula,
  .space .layer {
    animation: none;
  }
}
`;
fs.writeFileSync(new URL('../site/stars.css', import.meta.url), css);
console.log('site/stars.css');
