// npm run schema: writes src/sync-schema.js from schema/sync-payload.schema.json (#441).
//
// The JSON file is the sync payload's schema, the one the website pins a copy of. The
// extension's pages and its background worker load classic scripts, and the worker
// can't read a JSON file without a fetch, so src/sync-schema.js carries the same
// schema as a script (self.OHSyncSchema). Run this after changing the schema;
// test/sync-schema.test.js fails while the two differ.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const SCHEMA_FILE = 'schema/sync-payload.schema.json';
export const SCRIPT_FILE = 'src/sync-schema.js';

export async function schemaScript(json) {
  const text = `// Generated by scripts/sync-schema.mjs from ${SCHEMA_FILE}: don't edit it here.
// Change the JSON file and run \`npm run schema\` (test/sync-schema.test.js checks they
// match). The sync payload's schema (#441) for the dashboard, the background worker and
// Firefox's event page, as self.OHSyncSchema (frozen), read by src/schema-check.js.
(function (root) {
  const freeze = (v) => {
    if (v && typeof v === 'object') Object.values(Object.freeze(v)).forEach(freeze);
    return v;
  };
  const schema = freeze(${JSON.stringify(json)});
  root.OHSyncSchema = schema;
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof self !== 'undefined' ? self : globalThis);
`;
  const options = (await prettier.resolveConfig(ROOT + SCRIPT_FILE)) || {};
  return prettier.format(text, { ...options, filepath: ROOT + SCRIPT_FILE });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const json = JSON.parse(readFileSync(ROOT + SCHEMA_FILE, 'utf8'));
  writeFileSync(ROOT + SCRIPT_FILE, await schemaScript(json));
  console.log(`wrote ${SCRIPT_FILE} from ${SCHEMA_FILE}`);
}
