// Generated by scripts/sync-schema.mjs from schema/sync-payload.schema.json: don't edit it here.
// Change the JSON file and run `npm run schema` (test/sync-schema.test.js checks they
// match). The sync payload's schema (#441) for the dashboard, the background worker and
// Firefox's event page, as self.OHSyncSchema (frozen), read by src/schema-check.js.
(function (root) {
  const freeze = (v) => {
    if (v && typeof v === 'object') Object.values(Object.freeze(v)).forEach(freeze);
    return v;
  };
  const schema = freeze({
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://openhangar.space/schema/sync-payload/2',
    title: 'Open Hangar sync payload, format 2',
    description:
      "What the extension sends to openhangar.space when it syncs (#441): its backup file (format 2, schemaVersion) without the referral prospects list. `history` is optional: the hangar the website keeps, and the hangar view the extension hands our own hangar page, are this same shape without it. Containers whose keys the extension builds itself are strict; pledge and buy-back rows type the keys the extension and the website read and allow new ones. A value RSI reports that the extension passes on as it is (balances, country, recruits, referral counts) takes any simple value ($defs/scalar), so a type change on RSI's side can't stop sync. src/schema-check.js reads it and supports only the keywords used here.",
    type: 'object',
    required: ['app', 'appVersion', 'exportedAt', 'schemaVersion', 'account', 'sources'],
    additionalProperties: false,
    properties: {
      app: { const: 'open-hangar' },
      appVersion: {
        description: "The extension's version (its manifest), or null outside the extension.",
        type: ['string', 'null'],
        pattern: '^\\d+(\\.\\d+){0,3}$',
      },
      exportedAt: {
        description: 'When the payload was made, as Date.prototype.toISOString() writes it.',
        type: 'string',
        pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?Z$',
      },
      schemaVersion: { const: 2 },
      account: { $ref: '#/$defs/account' },
      sources: { $ref: '#/$defs/sources' },
      history: { $ref: '#/$defs/history' },
      pledgeArchive: { $ref: '#/$defs/pledgeArchive' },
    },
    $defs: {
      scalar: {
        description: 'A value RSI reports that the extension passes on as it is.',
        type: ['string', 'number', 'boolean', 'null'],
      },
      scanTime: {
        description:
          'When a source was scanned: milliseconds since 1970, a date string from an older backup, or null.',
        type: ['number', 'string', 'null'],
      },
      account: {
        description:
          'Who the hangar belongs to, from the RSI account the extension last read. Never the referral code.',
        type: ['object', 'null'],
        required: [
          'handle',
          'displayName',
          'avatar',
          'ueeRecord',
          'enlistedSince',
          'country',
          'organization',
          'subscriber',
          'concierge',
          'balances',
          'capturedAt',
        ],
        additionalProperties: false,
        properties: {
          handle: { type: ['string', 'null'] },
          displayName: { type: ['string', 'null'] },
          avatar: { type: ['string', 'null'] },
          ueeRecord: { type: ['string', 'null'] },
          enlistedSince: { $ref: '#/$defs/scalar' },
          country: { $ref: '#/$defs/scalar' },
          organization: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: {
              name: { type: ['string', 'null'] },
              sid: { type: ['string', 'null'] },
              rank: { type: ['string', 'null'] },
              logo: { type: ['string', 'null'] },
            },
          },
          subscriber: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: { type: { $ref: '#/$defs/scalar' }, frequency: { $ref: '#/$defs/scalar' } },
          },
          concierge: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: {
              level: { $ref: '#/$defs/scalar' },
              next: { $ref: '#/$defs/scalar' },
              percent: { $ref: '#/$defs/scalar' },
            },
          },
          balances: {
            type: ['object', 'null'],
            additionalProperties: false,
            properties: {
              storeCredit: { $ref: '#/$defs/credit' },
              uec: { $ref: '#/$defs/credit' },
              rec: { $ref: '#/$defs/credit' },
            },
          },
          capturedAt: { type: ['number', 'null'] },
        },
      },
      credit: {
        description:
          "A balance as RSI reports it, each value passed on as it is. Store Credit's value is in cents.",
        type: ['object', 'null'],
        additionalProperties: false,
        properties: {
          value: { $ref: '#/$defs/scalar' },
          currency: { $ref: '#/$defs/scalar' },
          symbol: { $ref: '#/$defs/scalar' },
          label: { $ref: '#/$defs/scalar' },
        },
      },
      sources: {
        description: 'The scanned sources. Each one is optional.',
        type: 'object',
        additionalProperties: false,
        properties: {
          hangar: {
            type: 'object',
            required: ['items'],
            additionalProperties: false,
            properties: {
              items: { type: 'array', items: { $ref: '#/$defs/pledge' } },
              scannedAt: { $ref: '#/$defs/scanTime' },
              meta: { $ref: '#/$defs/hangarMeta' },
            },
          },
          buybacks: {
            type: 'object',
            required: ['items'],
            additionalProperties: false,
            properties: {
              items: { type: 'array', items: { $ref: '#/$defs/buyback' } },
              scannedAt: { $ref: '#/$defs/scanTime' },
              meta: { $ref: '#/$defs/buybackMeta' },
            },
          },
          referral: {
            type: 'object',
            required: ['items'],
            additionalProperties: false,
            properties: {
              items: { $ref: '#/$defs/referral' },
              scannedAt: { $ref: '#/$defs/scanTime' },
              meta: {
                description: 'Nothing is kept next to a referral scan.',
                type: 'object',
                additionalProperties: false,
              },
            },
          },
        },
      },
      hangarMeta: {
        description:
          "What a complete hangar scan keeps next to its pledges: how completely it read RSI's page (shape), and what the next scan checks to skip an unchanged hangar (probe).",
        type: 'object',
        additionalProperties: false,
        properties: {
          shape: {
            type: 'object',
            additionalProperties: false,
            properties: {
              n: { type: 'number' },
              date: { type: 'number' },
              value: { type: 'number' },
              contents: { type: 'number' },
              image: { type: 'number' },
              tiles: { type: 'number' },
              untyped: { type: 'number' },
              guessed: { type: 'number' },
            },
          },
          probe: {
            type: 'object',
            additionalProperties: false,
            properties: {
              at: { type: 'number' },
              n: { type: 'number' },
              v: { type: ['string', 'null'] },
            },
          },
        },
      },
      buybackMeta: {
        description:
          "What a buy-back scan keeps next to its list: the buy-back tokens RSI's page shows, or null when it didn't say.",
        type: 'object',
        additionalProperties: false,
        properties: { tokens: { type: ['number', 'null'] } },
      },
      ccu: {
        description: "An upgrade's From and To ships.",
        type: ['object', 'null'],
        required: ['from', 'to'],
        additionalProperties: false,
        properties: { from: { type: 'string' }, to: { type: 'string' } },
      },
      content: {
        description: 'One thing inside a pledge.',
        type: 'object',
        properties: {
          kind: { type: 'string' },
          label: { type: 'string' },
          image: { type: ['string', 'null'] },
          guessed: { type: 'boolean' },
        },
      },
      pledge: {
        description: 'A pledge in the hangar, as the extension reads it from RSI.',
        type: 'object',
        required: ['id', 'name'],
        properties: {
          id: { type: ['string', 'number'] },
          name: { type: 'string' },
          value: { type: ['number', 'null'] },
          currency: { type: ['string', 'null'] },
          contents: { type: 'array', items: { $ref: '#/$defs/content' } },
          image: { type: ['string', 'null'] },
          containsShip: { type: 'boolean' },
          isCCU: { type: 'boolean' },
          ccu: { $ref: '#/$defs/ccu' },
          isAddOn: { type: 'boolean' },
          isCoupon: { type: 'boolean' },
          isPaint: { type: 'boolean' },
          kind: { type: 'string' },
          giftable: { type: 'boolean' },
          meltable: { type: 'boolean' },
          insurance: { type: ['string', 'null'] },
          date: { type: ['string', 'null'] },
          raw: { type: ['object', 'null'] },
        },
      },
      buyback: {
        description: "A pledge on RSI's buy-back list.",
        type: 'object',
        required: ['id', 'name'],
        properties: {
          id: { type: ['string', 'number'] },
          name: { type: 'string' },
          image: { type: ['string', 'null'] },
          date: { type: ['string', 'null'] },
          contains: { type: 'string' },
          href: { type: 'string' },
          price: { type: 'string' },
          isCCU: { type: 'boolean' },
          ccu: { $ref: '#/$defs/ccu' },
          wasUpgraded: { type: 'boolean' },
          fromShipId: { type: 'string' },
          toShipId: { type: 'string' },
          toSkuId: { type: 'string' },
          kind: { type: 'string' },
        },
      },
      recruitCount: {
        type: ['object', 'null'],
        properties: { recruits: { $ref: '#/$defs/scalar' } },
      },
      referral: {
        description:
          "Referral counts and recruits. Never the referral code or its link, and never the prospects list (other players who haven't joined yet): only their count.",
        type: 'object',
        additionalProperties: false,
        properties: {
          current: { $ref: '#/$defs/recruitCount' },
          legacy: { $ref: '#/$defs/recruitCount' },
          prospects: { $ref: '#/$defs/scalar' },
          recruitsList: { type: 'array', items: { $ref: '#/$defs/recruit' } },
        },
      },
      recruit: {
        description:
          'A recruit as RSI lists it, each value passed on as it is, and the campaign the extension tags it with.',
        type: 'object',
        properties: {
          id: { $ref: '#/$defs/scalar' },
          handle: { $ref: '#/$defs/scalar' },
          moniker: { $ref: '#/$defs/scalar' },
          avatar: { $ref: '#/$defs/scalar' },
          enlistedOn: { $ref: '#/$defs/scalar' },
          convertedOn: { $ref: '#/$defs/scalar' },
          campaign: { enum: ['current', 'legacy'] },
        },
      },
      history: {
        description: "Scan snapshots, oldest first: when, and each pledge's id, name and value.",
        type: 'array',
        items: {
          type: 'object',
          required: ['at', 'items'],
          additionalProperties: false,
          properties: {
            at: { type: 'number' },
            items: {
              type: 'array',
              items: {
                type: 'array',
                minItems: 3,
                prefixItems: [
                  { type: ['string', 'number'] },
                  { type: ['string', 'number'] },
                  { type: 'number' },
                ],
              },
            },
            credit: { type: 'number' },
            checkedAt: { type: 'number' },
          },
        },
      },
      pledgeArchive: {
        description: 'Pledges gone from the hangar, by pledge id: only what buy-back details read.',
        type: 'object',
        additionalProperties: { $ref: '#/$defs/archived' },
      },
      archived: {
        type: 'object',
        required: ['id', 'name'],
        additionalProperties: false,
        properties: {
          id: { type: 'string' },
          name: { type: 'string' },
          value: { type: 'number' },
          currency: { type: 'string' },
          insurance: { type: 'string' },
          ccu: { $ref: '#/$defs/ccu' },
          kind: { type: 'string' },
          date: { type: 'string' },
          contents: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              properties: { kind: { type: 'string' }, label: { type: 'string' } },
            },
          },
          goneAt: { type: 'number' },
        },
      },
    },
  });
  root.OHSyncSchema = schema;
  if (typeof module !== 'undefined' && module.exports) module.exports = schema;
})(typeof self !== 'undefined' ? self : globalThis);
